### ISSUE TITLE
[New Cog] Random Noa

### ISSUE THREAD

**Issue by JeffJrShim** [JeffJrShim/noa-cogs#5]
#### ToDo List
- [x] Upload all of the images to imgbb or a host and what not
- [x] Assign each link with 1 value/variable or something
- [ ] Making embeds with details about the card (trained and untrained)
- [x] Testing it with Peaky

PR can only be merged when all these are done, with all the commits done :3

**Comment by JeffJrShim** [comment]
Convo locked so no one can comment lol

**Comment by guacaplushy** [comment]
#11 first 2 cards all working, just needa add the rest.

**Comment by JeffJrShim** [comment]
#### ToDo List
- [x] Upload all of the images to imgbb or a host and what not
- [x] Assign each link with 1 value/variable or something
- [ ] Making embeds with details about the card (trained and untrained)
- [ ] Testing it with Peaky

PR can only be merged when all these are done, with all the commits done :3

**Comment by guacaplushy** [comment]
Feature added

**Comment by JeffJrShim** [comment]
Thanks buddy!
